name: Revert Wiki Changes Made Through the Web Interface
on:
  gollum

jobs:
  revert:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository_owner}}/test-oppia-docs
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0
      - name: Add deployment repository as a remote
        run: git remote add deployment https://github.com/${{github.repository_owner}}/test-oppia.wiki.git
      - name: Fetch remote
        run: git fetch deployment
      - name: Redeploy source
        run: git push -f deployment develop:master
