name: Revert Wiki Changes Made Through the Web Interface
on:
  gollum

jobs:
  revert:
    runs-on: ubuntu-18.04
    steps:
      - name: Retrieve authentication token
        id: get-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository_owner}}/test-oppia.wiki
          token: ${{ steps.get-token.outputs.token }}
          fetch-depth: 0
      - name: Add remote
        run: git remote add source https://github.com/${{github.repository_owner}}/test-oppia-docs.git
      - name: Fetch remote
        run: git fetch source
      - name: Check for differences
        id: check-diff
        run: echo "::set-output name=diff::$(git log source/develop..origin/master)"
      - name: Revert commits
        if: ${{ steps.check-diff.outputs.diff != '' }}
        run: |
          git config user.name test-wiki-revert[bot]
          git config user.email 97997431+test-wiki-revert[bot]@users.noreply.github.com
          git revert --no-edit source/develop..origin/master
      - name: Push to deployment repository
        if: ${{ steps.check-diff.outputs.diff != '' }}
        run: git push source master:develop
      - name: Push to source repository
        if: ${{ steps.check-diff.outputs.diff != '' }}
        run: git push
